# Generated by Django 5.0.6 on 2024-07-01 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_statement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='adress',
        ),
    ]
